// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd5p_onpnn1jGJTxufsIrNV0HpQ_E2ELY',
    appId: '1:231759824675:web:9055722c432016e818ae96',
    messagingSenderId: '231759824675',
    projectId: 'chatappforschool',
    authDomain: 'chatappforschool.firebaseapp.com',
    storageBucket: 'chatappforschool.appspot.com',
    measurementId: 'G-3CKQ07DK6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN5GVogk7vOhCnRQuH8LHeu_CpXQszQho',
    appId: '1:231759824675:android:e877e2024b60c4a918ae96',
    messagingSenderId: '231759824675',
    projectId: 'chatappforschool',
    storageBucket: 'chatappforschool.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJsp-YU6bj_QWmuLkXtsrOFG4s_qcGRk0',
    appId: '1:231759824675:ios:eea9430fe5844a2f18ae96',
    messagingSenderId: '231759824675',
    projectId: 'chatappforschool',
    storageBucket: 'chatappforschool.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJsp-YU6bj_QWmuLkXtsrOFG4s_qcGRk0',
    appId: '1:231759824675:ios:21d692bf8dc32f3218ae96',
    messagingSenderId: '231759824675',
    projectId: 'chatappforschool',
    storageBucket: 'chatappforschool.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
