name: chatapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  localstorage: ^4.0.1+4
  provider: ^6.0.5
  firebase_storage: ^11.2.8
  image_picker: ^1.0.4
  flutter_localizations:
    sdk: flutter
  flutter_phoenix: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: interFontFamily
      fonts:
        - asset: lib/fonts/Inter-Black.ttf
        - asset: lib/fonts/Inter-Bold.ttf
        - asset: lib/fonts/Inter-Light.ttf
        - asset: lib/fonts/Inter-Regular.ttf
        - asset: lib/fonts/Inter-Thin.ttf