name: Flutter Lint

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: flutter-action/setup-flutter@v2

      - name: Run Flutter Lint
        run: flutter analyze

      - name: Fail on lint errors
        if: ${{ steps.lint.outputs.error-count }} > 0
        uses: actions/github-script@v5
        with:
          script: |
            github.actions.createIssue({
              title: 'Lint errors found',
              body: 'Please fix the lint errors before merging this pull request.',
              assignees: ['@${{ github.actor }}']
            })
