name: Flutter Lint

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Flutter
        run: |
          docker run --rm -v $PWD:/app -w /app cirrusci/flutter:stable flutter pub get
        env:
          FLUTTER_ROOT: /usr/local/flutter

      - name: Run Lint
        run: |
          docker run --rm -v $PWD:/app -w /app cirrusci/flutter:stable flutter analyze
